<?php

use Illuminate\Database\Seeder;
use App\Kabupaten;

class KabupatenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Kabupaten::insert([
    ['id' => '1','kabupaten_id' => '1101','nama_kabupaten' => 'Aceh Selatan','provinsi_id' => '11'],
  ['id' => '2','kabupaten_id' => '1102','nama_kabupaten' => 'Aceh Tenggara','provinsi_id' => '11'],
  ['id' => '3','kabupaten_id' => '1103','nama_kabupaten' => 'Aceh Timur','provinsi_id' => '11'],
  ['id' => '4','kabupaten_id' => '1104','nama_kabupaten' => 'Aceh Tengah','provinsi_id' => '11'],
  ['id' => '5','kabupaten_id' => '1105','nama_kabupaten' => 'Aceh Barat','provinsi_id' => '11'],
  ['id' => '6','kabupaten_id' => '1106','nama_kabupaten' => 'Aceh Besar','provinsi_id' => '11'],
  ['id' => '7','kabupaten_id' => '1107','nama_kabupaten' => 'Pidie','provinsi_id' => '11'],
  ['id' => '8','kabupaten_id' => '1108','nama_kabupaten' => 'Aceh Utara','provinsi_id' => '11'],
  ['id' => '9','kabupaten_id' => '1109','nama_kabupaten' => 'Simeulue','provinsi_id' => '11'],
  ['id' => '10','kabupaten_id' => '1110','nama_kabupaten' => 'Aceh Singkil','provinsi_id' => '11'],
  ['id' => '11','kabupaten_id' => '1111','nama_kabupaten' => 'Bireuen','provinsi_id' => '11'],
  ['id' => '12','kabupaten_id' => '1112','nama_kabupaten' => 'Aceh Barat Daya','provinsi_id' => '11'],
  ['id' => '13','kabupaten_id' => '1113','nama_kabupaten' => 'Gayo Lues','provinsi_id' => '11'],
  ['id' => '14','kabupaten_id' => '1114','nama_kabupaten' => 'Aceh Jaya','provinsi_id' => '11'],
  ['id' => '15','kabupaten_id' => '1115','nama_kabupaten' => 'Nagan Raya','provinsi_id' => '11'],
  ['id' => '16','kabupaten_id' => '1116','nama_kabupaten' => 'Aceh Tamiang','provinsi_id' => '11'],
  ['id' => '17','kabupaten_id' => '1117','nama_kabupaten' => 'Bener Meriah','provinsi_id' => '11'],
  ['id' => '18','kabupaten_id' => '1118','nama_kabupaten' => 'Pidie Jaya','provinsi_id' => '11'],
  ['id' => '19','kabupaten_id' => '1171','nama_kabupaten' => 'Kota Banda Aceh','provinsi_id' => '11'],
  ['id' => '20','kabupaten_id' => '1172','nama_kabupaten' => 'Kota Sabang','provinsi_id' => '11'],
  ['id' => '21','kabupaten_id' => '1173','nama_kabupaten' => 'Kota Lhokseumawe','provinsi_id' => '11'],
  ['id' => '22','kabupaten_id' => '1174','nama_kabupaten' => 'Kota Langsa','provinsi_id' => '11'],
  ['id' => '23','kabupaten_id' => '1175','nama_kabupaten' => 'Kota Subulussalam','provinsi_id' => '11'],
  ['id' => '24','kabupaten_id' => '1201','nama_kabupaten' => 'Tapanuli Tengah','provinsi_id' => '12'],
  ['id' => '25','kabupaten_id' => '1202','nama_kabupaten' => 'Tapanuli Utara','provinsi_id' => '12'],
  ['id' => '26','kabupaten_id' => '1203','nama_kabupaten' => 'Tapanuli Selatan','provinsi_id' => '12'],
  ['id' => '27','kabupaten_id' => '1204','nama_kabupaten' => 'Nias','provinsi_id' => '12'],
  ['id' => '28','kabupaten_id' => '1205','nama_kabupaten' => 'Langkat','provinsi_id' => '12'],
  ['id' => '29','kabupaten_id' => '1206','nama_kabupaten' => 'Karo','provinsi_id' => '12'],
  ['id' => '30','kabupaten_id' => '1207','nama_kabupaten' => 'Deli Serdang','provinsi_id' => '12'],
  ['id' => '31','kabupaten_id' => '1209','nama_kabupaten' => 'Asahan','provinsi_id' => '12'],
  ['id' => '32','kabupaten_id' => '1208','nama_kabupaten' => 'Simalungun','provinsi_id' => '12'],
  ['id' => '33','kabupaten_id' => '1210','nama_kabupaten' => 'Labuhan Batu','provinsi_id' => '12'],
  ['id' => '34','kabupaten_id' => '1211','nama_kabupaten' => 'Dairi','provinsi_id' => '12'],
  ['id' => '35','kabupaten_id' => '1212','nama_kabupaten' => 'Toba Samosir','provinsi_id' => '12'],
  ['id' => '36','kabupaten_id' => '1217','nama_kabupaten' => 'Samosir','provinsi_id' => '12'],
  ['id' => '37','kabupaten_id' => '1213','nama_kabupaten' => 'Mandailing Natal','provinsi_id' => '12'],
  ['id' => '38','kabupaten_id' => '1214','nama_kabupaten' => 'Nias Selatan','provinsi_id' => '12'],
  ['id' => '39','kabupaten_id' => '1224','nama_kabupaten' => 'Nias Barat','provinsi_id' => '12'],
  ['id' => '40','kabupaten_id' => '1225','nama_kabupaten' => 'Nias Utara','provinsi_id' => '12'],
  ['id' => '41','kabupaten_id' => '1215','nama_kabupaten' => 'Pakpak Bharat','provinsi_id' => '12'],
  ['id' => '42','kabupaten_id' => '1216','nama_kabupaten' => 'Humbang Hasundutan','provinsi_id' => '12'],
  ['id' => '43','kabupaten_id' => '1218','nama_kabupaten' => 'Serdang Bedagai','provinsi_id' => '12'],
  ['id' => '44','kabupaten_id' => '1219','nama_kabupaten' => 'Padang Lawas','provinsi_id' => '12'],
  ['id' => '45','kabupaten_id' => '1306','nama_kabupaten' => 'Agam','provinsi_id' => '13'],
  ['id' => '46','kabupaten_id' => '1220','nama_kabupaten' => 'Padang Lawas Utara','provinsi_id' => '12'],
  ['id' => '47','kabupaten_id' => '1221','nama_kabupaten' => 'Batu Bara','provinsi_id' => '12'],
  ['id' => '48','kabupaten_id' => '1222','nama_kabupaten' => 'Labuhan Batu Selatan','provinsi_id' => '12'],
  ['id' => '49','kabupaten_id' => '1223','nama_kabupaten' => 'Labuhan Batu Utara','provinsi_id' => '12'],
  ['id' => '50','kabupaten_id' => '1401','nama_kabupaten' => 'Kampar','provinsi_id' => '14'],
  ['id' => '51','kabupaten_id' => '1271','nama_kabupaten' => 'Kota Medan','provinsi_id' => '12'],
  ['id' => '52','kabupaten_id' => '1272','nama_kabupaten' => 'Kota Pematang Siantar','provinsi_id' => '12'],
  ['id' => '53','kabupaten_id' => '1273','nama_kabupaten' => 'Kota Sibolga','provinsi_id' => '12'],
  ['id' => '54','kabupaten_id' => '1274','nama_kabupaten' => 'Kota Tanjung Balai','provinsi_id' => '12'],
  ['id' => '55','kabupaten_id' => '1275','nama_kabupaten' => 'Kota Binjai','provinsi_id' => '12'],
  ['id' => '56','kabupaten_id' => '1276','nama_kabupaten' => 'Kota Tebing Tinggi','provinsi_id' => '12'],
  ['id' => '57','kabupaten_id' => '1277','nama_kabupaten' => 'Kota Padang Sidempuan','provinsi_id' => '12'],
  ['id' => '58','kabupaten_id' => '1278','nama_kabupaten' => 'Kota Gunungsitoli','provinsi_id' => '12'],
  ['id' => '59','kabupaten_id' => '1301','nama_kabupaten' => 'Pesisir Selatan','provinsi_id' => '13'],
  ['id' => '60','kabupaten_id' => '1302','nama_kabupaten' => 'Solok','provinsi_id' => '13'],
  ['id' => '61','kabupaten_id' => '1303','nama_kabupaten' => 'Sijunjung','provinsi_id' => '13'],
  ['id' => '62','kabupaten_id' => '1304','nama_kabupaten' => 'Tanah Datar','provinsi_id' => '13'],
  ['id' => '63','kabupaten_id' => '1305','nama_kabupaten' => 'Padang Pariaman','provinsi_id' => '13'],
  ['id' => '64','kabupaten_id' => '1307','nama_kabupaten' => 'Lima Puluh Kota','provinsi_id' => '13'],
  ['id' => '65','kabupaten_id' => '1308','nama_kabupaten' => 'Pasaman','provinsi_id' => '13'],
  ['id' => '66','kabupaten_id' => '1309','nama_kabupaten' => 'Kepulauan Mentawai','provinsi_id' => '13'],
  ['id' => '67','kabupaten_id' => '1310','nama_kabupaten' => 'Dharmasraya','provinsi_id' => '13'],
  ['id' => '68','kabupaten_id' => '1311','nama_kabupaten' => 'Solok Selatan','provinsi_id' => '13'],
  ['id' => '69','kabupaten_id' => '1312','nama_kabupaten' => 'Pasaman Barat','provinsi_id' => '13'],
  ['id' => '70','kabupaten_id' => '1371','nama_kabupaten' => 'Kota Padang','provinsi_id' => '13'],
  ['id' => '71','kabupaten_id' => '1372','nama_kabupaten' => 'Kota Solok','provinsi_id' => '13'],
  ['id' => '72','kabupaten_id' => '1373','nama_kabupaten' => 'Kota Sawah Lunto','provinsi_id' => '13'],
  ['id' => '73','kabupaten_id' => '1374','nama_kabupaten' => 'Kota Padang Panjang','provinsi_id' => '13'],
  ['id' => '74','kabupaten_id' => '1375','nama_kabupaten' => 'Kota Bukittinggi','provinsi_id' => '13'],
  ['id' => '75','kabupaten_id' => '1376','nama_kabupaten' => 'Kota Payakumbuh','provinsi_id' => '13'],
  ['id' => '76','kabupaten_id' => '1377','nama_kabupaten' => 'Kota Pariaman','provinsi_id' => '13'],
  ['id' => '77','kabupaten_id' => '1402','nama_kabupaten' => 'Indragiri Hulu','provinsi_id' => '14'],
  ['id' => '78','kabupaten_id' => '1403','nama_kabupaten' => 'Bengkalis','provinsi_id' => '14'],
  ['id' => '79','kabupaten_id' => '1404','nama_kabupaten' => 'Indragiri Hilir','provinsi_id' => '14'],
  ['id' => '80','kabupaten_id' => '1405','nama_kabupaten' => 'Pelalawan','provinsi_id' => '14'],
  ['id' => '81','kabupaten_id' => '1406','nama_kabupaten' => 'Rokan Hulu','provinsi_id' => '14'],
  ['id' => '82','kabupaten_id' => '1407','nama_kabupaten' => 'Rokan Hilir','provinsi_id' => '14'],
  ['id' => '83','kabupaten_id' => '1408','nama_kabupaten' => 'Siak','provinsi_id' => '14'],
  ['id' => '84','kabupaten_id' => '1409','nama_kabupaten' => 'Kuantan Singingi','provinsi_id' => '14'],
  ['id' => '85','kabupaten_id' => '1410','nama_kabupaten' => 'Kepulauan Meranti','provinsi_id' => '14'],
  ['id' => '86','kabupaten_id' => '1471','nama_kabupaten' => 'Kota Pekanbaru','provinsi_id' => '14'],
  ['id' => '87','kabupaten_id' => '1472','nama_kabupaten' => 'Kota Dumai','provinsi_id' => '14'],
  ['id' => '88','kabupaten_id' => '1501','nama_kabupaten' => 'Kerinci','provinsi_id' => '15'],
  ['id' => '89','kabupaten_id' => '1502','nama_kabupaten' => 'Merangin','provinsi_id' => '15'],
  ['id' => '90','kabupaten_id' => '1503','nama_kabupaten' => 'Sarolangun','provinsi_id' => '15'],
  ['id' => '91','kabupaten_id' => '1504','nama_kabupaten' => 'Batang Hari','provinsi_id' => '15'],
  ['id' => '92','kabupaten_id' => '1505','nama_kabupaten' => 'Muaro Jambi','provinsi_id' => '15'],
  ['id' => '93','kabupaten_id' => '1506','nama_kabupaten' => 'Tanjung Jabung Barat','provinsi_id' => '15'],
  ['id' => '94','kabupaten_id' => '1507','nama_kabupaten' => 'Tanjung Jabung Timur','provinsi_id' => '15'],
  ['id' => '95','kabupaten_id' => '1508','nama_kabupaten' => 'Bungo','provinsi_id' => '15'],
  ['id' => '96','kabupaten_id' => '1509','nama_kabupaten' => 'Tebo','provinsi_id' => '15'],
  ['id' => '97','kabupaten_id' => '1571','nama_kabupaten' => 'Kota Jambi','provinsi_id' => '15'],
  ['id' => '98','kabupaten_id' => '1572','nama_kabupaten' => 'Kota Sungaipenuh','provinsi_id' => '15'],
  ['id' => '99','kabupaten_id' => '1601','nama_kabupaten' => 'Ogan Komering Ulu','provinsi_id' => '16'],
  ['id' => '100','kabupaten_id' => '1602','nama_kabupaten' => 'Ogan Komering Ilir','provinsi_id' => '16'],
  ['id' => '101','kabupaten_id' => '1603','nama_kabupaten' => 'Muara Enim','provinsi_id' => '16'],
  ['id' => '102','kabupaten_id' => '1604','nama_kabupaten' => 'Lahat','provinsi_id' => '16'],
  ['id' => '103','kabupaten_id' => '1704','nama_kabupaten' => 'Kaur','provinsi_id' => '17'],
  ['id' => '104','kabupaten_id' => '1605','nama_kabupaten' => 'Musi Rawas','provinsi_id' => '16'],
  ['id' => '105','kabupaten_id' => '1606','nama_kabupaten' => 'Musi Banyuasin','provinsi_id' => '16'],
  ['id' => '106','kabupaten_id' => '1607','nama_kabupaten' => 'Banyuasin','provinsi_id' => '16'],
  ['id' => '107','kabupaten_id' => '1608','nama_kabupaten' => 'Ogan Komering Ulu Timur','provinsi_id' => '16'],
  ['id' => '108','kabupaten_id' => '1609','nama_kabupaten' => 'Ogan Komering Ulu Selatan','provinsi_id' => '16'],
  ['id' => '109','kabupaten_id' => '1610','nama_kabupaten' => 'Ogan Ilir','provinsi_id' => '16'],
  ['id' => '110','kabupaten_id' => '1611','nama_kabupaten' => 'Empat Lawang','provinsi_id' => '16'],
  ['id' => '111','kabupaten_id' => '1612','nama_kabupaten' => 'Penukal Abab Lematang Ilir','provinsi_id' => '16'],
  ['id' => '112','kabupaten_id' => '1613','nama_kabupaten' => 'Musi Rawas Utara','provinsi_id' => '16'],
  ['id' => '113','kabupaten_id' => '1671','nama_kabupaten' => 'Kota Palembang','provinsi_id' => '16'],
  ['id' => '114','kabupaten_id' => '1672','nama_kabupaten' => 'Kota Pagar Alam','provinsi_id' => '16'],
  ['id' => '115','kabupaten_id' => '1673','nama_kabupaten' => 'Kota Lubuklinggau','provinsi_id' => '16'],
  ['id' => '116','kabupaten_id' => '1674','nama_kabupaten' => 'Kota Prabumulih','provinsi_id' => '16'],
  ['id' => '117','kabupaten_id' => '1701','nama_kabupaten' => 'Bengkulu Selatan','provinsi_id' => '17'],
  ['id' => '118','kabupaten_id' => '1702','nama_kabupaten' => 'Rejang Lebong','provinsi_id' => '17'],
  ['id' => '119','kabupaten_id' => '1703','nama_kabupaten' => 'Bengkulu Utara','provinsi_id' => '17'],
  ['id' => '120','kabupaten_id' => '1705','nama_kabupaten' => 'Seluma','provinsi_id' => '17'],
  ['id' => '121','kabupaten_id' => '1706','nama_kabupaten' => 'Mukomuko','provinsi_id' => '17'],
  ['id' => '122','kabupaten_id' => '1707','nama_kabupaten' => 'Lebong','provinsi_id' => '17'],
  ['id' => '123','kabupaten_id' => '1708','nama_kabupaten' => 'Kepahiang','provinsi_id' => '17'],
  ['id' => '124','kabupaten_id' => '1709','nama_kabupaten' => 'Bengkulu Tengah','provinsi_id' => '17'],
  ['id' => '125','kabupaten_id' => '1771','nama_kabupaten' => 'Kota Bengkulu','provinsi_id' => '17'],
  ['id' => '126','kabupaten_id' => '1801','nama_kabupaten' => 'Lampung Selatan','provinsi_id' => '18'],
  ['id' => '127','kabupaten_id' => '1802','nama_kabupaten' => 'Lampung Tengah','provinsi_id' => '18'],
  ['id' => '128','kabupaten_id' => '1803','nama_kabupaten' => 'Lampung Utara','provinsi_id' => '18'],
  ['id' => '129','kabupaten_id' => '1804','nama_kabupaten' => 'Lampung Barat','provinsi_id' => '18'],
  ['id' => '130','kabupaten_id' => '1805','nama_kabupaten' => 'Tulangbawang','provinsi_id' => '18'],
  ['id' => '131','kabupaten_id' => '1806','nama_kabupaten' => 'Tanggamus','provinsi_id' => '18'],
  ['id' => '132','kabupaten_id' => '1807','nama_kabupaten' => 'Lampung Timur','provinsi_id' => '18'],
  ['id' => '133','kabupaten_id' => '1808','nama_kabupaten' => 'Way Kanan','provinsi_id' => '18'],
  ['id' => '134','kabupaten_id' => '1809','nama_kabupaten' => 'Pesawaran','provinsi_id' => '18'],
  ['id' => '135','kabupaten_id' => '1810','nama_kabupaten' => 'Pringsewu','provinsi_id' => '18'],
  ['id' => '136','kabupaten_id' => '1811','nama_kabupaten' => 'Tulang Bawang Barat','provinsi_id' => '18'],
  ['id' => '137','kabupaten_id' => '1812','nama_kabupaten' => 'Mesuji','provinsi_id' => '18'],
  ['id' => '138','kabupaten_id' => '1813','nama_kabupaten' => 'Pesisir Barat','provinsi_id' => '18'],
  ['id' => '139','kabupaten_id' => '1871','nama_kabupaten' => 'Kota Bandar Lampung','provinsi_id' => '18'],
  ['id' => '140','kabupaten_id' => '2102','nama_kabupaten' => 'Karimun','provinsi_id' => '21'],
  ['id' => '141','kabupaten_id' => '1872','nama_kabupaten' => 'Kota Metro','provinsi_id' => '18'],
  ['id' => '142','kabupaten_id' => '1901','nama_kabupaten' => 'Bangka','provinsi_id' => '19'],
  ['id' => '143','kabupaten_id' => '1902','nama_kabupaten' => 'Belitung','provinsi_id' => '19'],
  ['id' => '144','kabupaten_id' => '1903','nama_kabupaten' => 'Bangka Selatan','provinsi_id' => '19'],
  ['id' => '145','kabupaten_id' => '1904','nama_kabupaten' => 'Bangka Tengah','provinsi_id' => '19'],
  ['id' => '146','kabupaten_id' => '1905','nama_kabupaten' => 'Bangka Barat','provinsi_id' => '19'],
  ['id' => '147','kabupaten_id' => '1906','nama_kabupaten' => 'Belitung Timur','provinsi_id' => '19'],
  ['id' => '148','kabupaten_id' => '1971','nama_kabupaten' => 'Kota Pangkal Pinang','provinsi_id' => '19'],
  ['id' => '149','kabupaten_id' => '2101','nama_kabupaten' => 'Bintan','provinsi_id' => '21'],
  ['id' => '150','kabupaten_id' => '2103','nama_kabupaten' => 'Natuna','provinsi_id' => '21'],
  ['id' => '151','kabupaten_id' => '2104','nama_kabupaten' => 'Lingga','provinsi_id' => '21'],
  ['id' => '152','kabupaten_id' => '2105','nama_kabupaten' => 'Kepulauan Anambas','provinsi_id' => '21'],
  ['id' => '153','kabupaten_id' => '2171','nama_kabupaten' => 'Kota Batam','provinsi_id' => '21'],
  ['id' => '154','kabupaten_id' => '3201','nama_kabupaten' => 'Bogor','provinsi_id' => '32'],
  ['id' => '155','kabupaten_id' => '2172','nama_kabupaten' => 'Kota Tanjung Pinang','provinsi_id' => '21'],
  ['id' => '156','kabupaten_id' => '3101','nama_kabupaten' => 'Kepulauan Seribu','provinsi_id' => '31'],
  ['id' => '157','kabupaten_id' => '3171','nama_kabupaten' => 'Kota Jakarta Pusat','provinsi_id' => '31'],
  ['id' => '158','kabupaten_id' => '3172','nama_kabupaten' => 'Kota Jakarta Utara','provinsi_id' => '31'],
  ['id' => '159','kabupaten_id' => '3173','nama_kabupaten' => 'Kota Jakarta Barat','provinsi_id' => '31'],
  ['id' => '160','kabupaten_id' => '3174','nama_kabupaten' => 'Kota Jakarta Selatan','provinsi_id' => '31'],
  ['id' => '161','kabupaten_id' => '3175','nama_kabupaten' => 'Kota Jakarta Timur','provinsi_id' => '31'],
  ['id' => '162','kabupaten_id' => '3202','nama_kabupaten' => 'Sukabumi','provinsi_id' => '32'],
  ['id' => '163','kabupaten_id' => '3203','nama_kabupaten' => 'Cianjur','provinsi_id' => '32'],
  ['id' => '164','kabupaten_id' => '3204','nama_kabupaten' => 'Bandung','provinsi_id' => '32'],
  ['id' => '165','kabupaten_id' => '3205','nama_kabupaten' => 'Garut','provinsi_id' => '32'],
  ['id' => '166','kabupaten_id' => '3206','nama_kabupaten' => 'Tasikmalaya','provinsi_id' => '32'],
  ['id' => '167','kabupaten_id' => '3207','nama_kabupaten' => 'Ciamis','provinsi_id' => '32'],
  ['id' => '168','kabupaten_id' => '3208','nama_kabupaten' => 'Kuningan','provinsi_id' => '32'],
  ['id' => '169','kabupaten_id' => '3209','nama_kabupaten' => 'Cirebon','provinsi_id' => '32'],
  ['id' => '170','kabupaten_id' => '3210','nama_kabupaten' => 'Majalengka','provinsi_id' => '32'],
  ['id' => '171','kabupaten_id' => '3211','nama_kabupaten' => 'Sumedang','provinsi_id' => '32'],
  ['id' => '172','kabupaten_id' => '3212','nama_kabupaten' => 'Indramayu','provinsi_id' => '32'],
  ['id' => '173','kabupaten_id' => '3213','nama_kabupaten' => 'Subang','provinsi_id' => '32'],
  ['id' => '174','kabupaten_id' => '3214','nama_kabupaten' => 'Purwakarta','provinsi_id' => '32'],
  ['id' => '175','kabupaten_id' => '3215','nama_kabupaten' => 'Karawang','provinsi_id' => '32'],
  ['id' => '176','kabupaten_id' => '3216','nama_kabupaten' => 'Bekasi','provinsi_id' => '32'],
  ['id' => '177','kabupaten_id' => '3217','nama_kabupaten' => 'Bandung Barat','provinsi_id' => '32'],
  ['id' => '178','kabupaten_id' => '3218','nama_kabupaten' => 'Pangandaran','provinsi_id' => '32'],
  ['id' => '179','kabupaten_id' => '3271','nama_kabupaten' => 'Kota Bogor','provinsi_id' => '32'],
  ['id' => '180','kabupaten_id' => '3272','nama_kabupaten' => 'Kota Sukabumi','provinsi_id' => '32'],
  ['id' => '181','kabupaten_id' => '3273','nama_kabupaten' => 'Kota Bandung','provinsi_id' => '32'],
  ['id' => '182','kabupaten_id' => '3274','nama_kabupaten' => 'Kota Cirebon','provinsi_id' => '32'],
  ['id' => '183','kabupaten_id' => '3275','nama_kabupaten' => 'Kota Bekasi','provinsi_id' => '32'],
  ['id' => '184','kabupaten_id' => '3276','nama_kabupaten' => 'Kota Depok','provinsi_id' => '32'],
  ['id' => '185','kabupaten_id' => '3277','nama_kabupaten' => 'Kota Cimahi','provinsi_id' => '32'],
  ['id' => '186','kabupaten_id' => '3278','nama_kabupaten' => 'Kota Tasikmalaya','provinsi_id' => '32'],
  ['id' => '187','kabupaten_id' => '3279','nama_kabupaten' => 'Kota Banjar','provinsi_id' => '32'],
  ['id' => '188','kabupaten_id' => '3301','nama_kabupaten' => 'Cilacap','provinsi_id' => '33'],
  ['id' => '189','kabupaten_id' => '3302','nama_kabupaten' => 'Banyumas','provinsi_id' => '33'],
  ['id' => '190','kabupaten_id' => '3303','nama_kabupaten' => 'Purbalingga','provinsi_id' => '33'],
  ['id' => '191','kabupaten_id' => '3304','nama_kabupaten' => 'Banjarnegara','provinsi_id' => '33'],
  ['id' => '192','kabupaten_id' => '3305','nama_kabupaten' => 'Kebumen','provinsi_id' => '33'],
  ['id' => '193','kabupaten_id' => '3306','nama_kabupaten' => 'Purworejo','provinsi_id' => '33'],
  ['id' => '194','kabupaten_id' => '3307','nama_kabupaten' => 'Wonosobo','provinsi_id' => '33'],
  ['id' => '195','kabupaten_id' => '3308','nama_kabupaten' => 'Magelang','provinsi_id' => '33'],
  ['id' => '196','kabupaten_id' => '3309','nama_kabupaten' => 'Boyolali','provinsi_id' => '33'],
  ['id' => '197','kabupaten_id' => '3310','nama_kabupaten' => 'Klaten','provinsi_id' => '33'],
  ['id' => '198','kabupaten_id' => '3311','nama_kabupaten' => 'Sukoharjo','provinsi_id' => '33'],
  ['id' => '199','kabupaten_id' => '3312','nama_kabupaten' => 'Wonogiri','provinsi_id' => '33'],
  ['id' => '200','kabupaten_id' => '3313','nama_kabupaten' => 'Karanganyar','provinsi_id' => '33'],
  ['id' => '201','kabupaten_id' => '3314','nama_kabupaten' => 'Sragen','provinsi_id' => '33'],
  ['id' => '202','kabupaten_id' => '3315','nama_kabupaten' => 'Grobogan','provinsi_id' => '33'],
  ['id' => '203','kabupaten_id' => '3316','nama_kabupaten' => 'Blora','provinsi_id' => '33'],
  ['id' => '204','kabupaten_id' => '3317','nama_kabupaten' => 'Rembang','provinsi_id' => '33'],
  ['id' => '205','kabupaten_id' => '3318','nama_kabupaten' => 'Pati','provinsi_id' => '33'],
  ['id' => '206','kabupaten_id' => '3319','nama_kabupaten' => 'Kudus','provinsi_id' => '33'],
  ['id' => '207','kabupaten_id' => '3320','nama_kabupaten' => 'Jepara','provinsi_id' => '33'],
  ['id' => '208','kabupaten_id' => '3321','nama_kabupaten' => 'Demak','provinsi_id' => '33'],
  ['id' => '209','kabupaten_id' => '3322','nama_kabupaten' => 'Semarang','provinsi_id' => '33'],
  ['id' => '210','kabupaten_id' => '3323','nama_kabupaten' => 'Temanggung','provinsi_id' => '33'],
  ['id' => '211','kabupaten_id' => '3324','nama_kabupaten' => 'Kendal','provinsi_id' => '33'],
  ['id' => '212','kabupaten_id' => '3325','nama_kabupaten' => 'Batang','provinsi_id' => '33'],
  ['id' => '213','kabupaten_id' => '3326','nama_kabupaten' => 'Pekalongan','provinsi_id' => '33'],
  ['id' => '214','kabupaten_id' => '3327','nama_kabupaten' => 'Pemalang','provinsi_id' => '33'],
  ['id' => '215','kabupaten_id' => '3328','nama_kabupaten' => 'Tegal','provinsi_id' => '33'],
  ['id' => '216','kabupaten_id' => '3329','nama_kabupaten' => 'Brebes','provinsi_id' => '33'],
  ['id' => '217','kabupaten_id' => '3371','nama_kabupaten' => 'Kota Magelang','provinsi_id' => '33'],
  ['id' => '218','kabupaten_id' => '3372','nama_kabupaten' => 'Kota Surakarta','provinsi_id' => '33'],
  ['id' => '219','kabupaten_id' => '3373','nama_kabupaten' => 'Kota Salatiga','provinsi_id' => '33'],
  ['id' => '220','kabupaten_id' => '3374','nama_kabupaten' => 'Kota Semarang','provinsi_id' => '33'],
  ['id' => '221','kabupaten_id' => '3375','nama_kabupaten' => 'Kota Pekalongan','provinsi_id' => '33'],
  ['id' => '222','kabupaten_id' => '3402','nama_kabupaten' => 'Bantul','provinsi_id' => '34'],
  ['id' => '223','kabupaten_id' => '3376','nama_kabupaten' => 'Kota Tegal','provinsi_id' => '33'],
  ['id' => '224','kabupaten_id' => '3401','nama_kabupaten' => 'Kulon Progo','provinsi_id' => '34'],
  ['id' => '225','kabupaten_id' => '3403','nama_kabupaten' => 'Gunung Kidul','provinsi_id' => '34'],
  ['id' => '226','kabupaten_id' => '3404','nama_kabupaten' => 'Sleman','provinsi_id' => '34'],
  ['id' => '227','kabupaten_id' => '3471','nama_kabupaten' => 'Kota Yogyakarta','provinsi_id' => '34'],
  ['id' => '228','kabupaten_id' => '3501','nama_kabupaten' => 'Pacitan','provinsi_id' => '35'],
  ['id' => '229','kabupaten_id' => '3502','nama_kabupaten' => 'Ponorogo','provinsi_id' => '35'],
  ['id' => '230','kabupaten_id' => '3503','nama_kabupaten' => 'Trenggalek','provinsi_id' => '35'],
  ['id' => '231','kabupaten_id' => '3504','nama_kabupaten' => 'Tulungagung','provinsi_id' => '35'],
  ['id' => '232','kabupaten_id' => '3505','nama_kabupaten' => 'Blitar','provinsi_id' => '35'],
  ['id' => '233','kabupaten_id' => '3506','nama_kabupaten' => 'Kediri','provinsi_id' => '35'],
  ['id' => '234','kabupaten_id' => '3507','nama_kabupaten' => 'Malang','provinsi_id' => '35'],
  ['id' => '235','kabupaten_id' => '3508','nama_kabupaten' => 'Lumajang','provinsi_id' => '35'],
  ['id' => '236','kabupaten_id' => '3509','nama_kabupaten' => 'Jember','provinsi_id' => '35'],
  ['id' => '237','kabupaten_id' => '3510','nama_kabupaten' => 'Banyuwangi','provinsi_id' => '35'],
  ['id' => '238','kabupaten_id' => '3511','nama_kabupaten' => 'Bondowoso','provinsi_id' => '35'],
  ['id' => '239','kabupaten_id' => '3512','nama_kabupaten' => 'Situbondo','provinsi_id' => '35'],
  ['id' => '240','kabupaten_id' => '3513','nama_kabupaten' => 'Probolinggo','provinsi_id' => '35'],
  ['id' => '241','kabupaten_id' => '3514','nama_kabupaten' => 'Pasuruan','provinsi_id' => '35'],
  ['id' => '242','kabupaten_id' => '3515','nama_kabupaten' => 'Sidoarjo','provinsi_id' => '35'],
  ['id' => '243','kabupaten_id' => '3516','nama_kabupaten' => 'Mojokerto','provinsi_id' => '35'],
  ['id' => '244','kabupaten_id' => '3517','nama_kabupaten' => 'Jombang','provinsi_id' => '35'],
  ['id' => '245','kabupaten_id' => '3518','nama_kabupaten' => 'Nganjuk','provinsi_id' => '35'],
  ['id' => '246','kabupaten_id' => '3519','nama_kabupaten' => 'Madiun','provinsi_id' => '35'],
  ['id' => '247','kabupaten_id' => '3520','nama_kabupaten' => 'Magetan','provinsi_id' => '35'],
  ['id' => '248','kabupaten_id' => '3521','nama_kabupaten' => 'Ngawi','provinsi_id' => '35'],
  ['id' => '249','kabupaten_id' => '3522','nama_kabupaten' => 'Bojonegoro','provinsi_id' => '35'],
  ['id' => '250','kabupaten_id' => '3523','nama_kabupaten' => 'Tuban','provinsi_id' => '35'],
  ['id' => '251','kabupaten_id' => '3524','nama_kabupaten' => 'Lamongan','provinsi_id' => '35'],
  ['id' => '252','kabupaten_id' => '3525','nama_kabupaten' => 'Gresik','provinsi_id' => '35'],
  ['id' => '253','kabupaten_id' => '3526','nama_kabupaten' => 'Bangkalan','provinsi_id' => '35'],
  ['id' => '254','kabupaten_id' => '3527','nama_kabupaten' => 'Sampang','provinsi_id' => '35'],
  ['id' => '255','kabupaten_id' => '3528','nama_kabupaten' => 'Pamekasan','provinsi_id' => '35'],
  ['id' => '256','kabupaten_id' => '3529','nama_kabupaten' => 'Sumenep','provinsi_id' => '35'],
  ['id' => '257','kabupaten_id' => '3571','nama_kabupaten' => 'Kota Kediri','provinsi_id' => '35'],
  ['id' => '258','kabupaten_id' => '3572','nama_kabupaten' => 'Kota Blitar','provinsi_id' => '35'],
  ['id' => '259','kabupaten_id' => '3573','nama_kabupaten' => 'Kota Malang','provinsi_id' => '35'],
  ['id' => '260','kabupaten_id' => '3577','nama_kabupaten' => 'Kota Madiun','provinsi_id' => '35'],
  ['id' => '261','kabupaten_id' => '3574','nama_kabupaten' => 'Kota Probolinggo','provinsi_id' => '35'],
  ['id' => '262','kabupaten_id' => '3575','nama_kabupaten' => 'Kota Pasuruan','provinsi_id' => '35'],
  ['id' => '263','kabupaten_id' => '3576','nama_kabupaten' => 'Kota Mojokerto','provinsi_id' => '35'],
  ['id' => '264','kabupaten_id' => '3578','nama_kabupaten' => 'Kota Surabaya','provinsi_id' => '35'],
  ['id' => '265','kabupaten_id' => '3579','nama_kabupaten' => 'Kota Batu','provinsi_id' => '35'],
  ['id' => '266','kabupaten_id' => '3601','nama_kabupaten' => 'Pandeglang','provinsi_id' => '36'],
  ['id' => '267','kabupaten_id' => '3602','nama_kabupaten' => 'Lebak','provinsi_id' => '36'],
  ['id' => '268','kabupaten_id' => '3603','nama_kabupaten' => 'Tangerang','provinsi_id' => '36'],
  ['id' => '269','kabupaten_id' => '3604','nama_kabupaten' => 'Serang','provinsi_id' => '36'],
  ['id' => '270','kabupaten_id' => '3671','nama_kabupaten' => 'Kota Tangerang','provinsi_id' => '36'],
  ['id' => '271','kabupaten_id' => '3672','nama_kabupaten' => 'Kota Cilegon','provinsi_id' => '36'],
  ['id' => '272','kabupaten_id' => '3673','nama_kabupaten' => 'Kota Serang','provinsi_id' => '36'],
  ['id' => '273','kabupaten_id' => '3674','nama_kabupaten' => 'Kota Tangerang Selatan','provinsi_id' => '36'],
  ['id' => '274','kabupaten_id' => '5101','nama_kabupaten' => 'Jembrana','provinsi_id' => '51'],
  ['id' => '275','kabupaten_id' => '5102','nama_kabupaten' => 'Tabanan','provinsi_id' => '51'],
  ['id' => '276','kabupaten_id' => '5103','nama_kabupaten' => 'Badung','provinsi_id' => '51'],
  ['id' => '277','kabupaten_id' => '5104','nama_kabupaten' => 'Gianyar','provinsi_id' => '51'],
  ['id' => '278','kabupaten_id' => '5105','nama_kabupaten' => 'Klungkung','provinsi_id' => '51'],
  ['id' => '279','kabupaten_id' => '5106','nama_kabupaten' => 'Bangli','provinsi_id' => '51'],
  ['id' => '280','kabupaten_id' => '5107','nama_kabupaten' => 'Karang Asem','provinsi_id' => '51'],
  ['id' => '281','kabupaten_id' => '5108','nama_kabupaten' => 'Buleleng','provinsi_id' => '51'],
  ['id' => '282','kabupaten_id' => '5171','nama_kabupaten' => 'Kota Denpasar','provinsi_id' => '51'],
  ['id' => '283','kabupaten_id' => '5201','nama_kabupaten' => 'Lombok Barat','provinsi_id' => '52'],
  ['id' => '284','kabupaten_id' => '5202','nama_kabupaten' => 'Lombok Tengah','provinsi_id' => '52'],
  ['id' => '285','kabupaten_id' => '5205','nama_kabupaten' => 'Dompu','provinsi_id' => '52'],
  ['id' => '286','kabupaten_id' => '5203','nama_kabupaten' => 'Lombok Timur','provinsi_id' => '52'],
  ['id' => '287','kabupaten_id' => '5204','nama_kabupaten' => 'Sumbawa','provinsi_id' => '52'],
  ['id' => '288','kabupaten_id' => '5206','nama_kabupaten' => 'Bima','provinsi_id' => '52'],
  ['id' => '289','kabupaten_id' => '5207','nama_kabupaten' => 'Sumbawa Barat','provinsi_id' => '52'],
  ['id' => '290','kabupaten_id' => '5208','nama_kabupaten' => 'Lombok Utara','provinsi_id' => '52'],
  ['id' => '291','kabupaten_id' => '5271','nama_kabupaten' => 'Kota Mataram','provinsi_id' => '52'],
  ['id' => '292','kabupaten_id' => '5272','nama_kabupaten' => 'Kota Bima','provinsi_id' => '52'],
  ['id' => '293','kabupaten_id' => '5301','nama_kabupaten' => 'Kupang','provinsi_id' => '53'],
  ['id' => '294','kabupaten_id' => '5302','nama_kabupaten' => 'Timor Tengah Selatan','provinsi_id' => '53'],
  ['id' => '295','kabupaten_id' => '5307','nama_kabupaten' => 'Sikka','provinsi_id' => '53'],
  ['id' => '296','kabupaten_id' => '5303','nama_kabupaten' => 'Timor Tengah Utara','provinsi_id' => '53'],
  ['id' => '297','kabupaten_id' => '5304','nama_kabupaten' => 'Belu','provinsi_id' => '53'],
  ['id' => '298','kabupaten_id' => '5305','nama_kabupaten' => 'Alor','provinsi_id' => '53'],
  ['id' => '299','kabupaten_id' => '5306','nama_kabupaten' => 'Flores Timur','provinsi_id' => '53'],
  ['id' => '300','kabupaten_id' => '5308','nama_kabupaten' => 'Ende','provinsi_id' => '53'],
  ['id' => '301','kabupaten_id' => '5309','nama_kabupaten' => 'Ngada','provinsi_id' => '53'],
  ['id' => '302','kabupaten_id' => '5310','nama_kabupaten' => 'Manggarai','provinsi_id' => '53'],
  ['id' => '303','kabupaten_id' => '5311','nama_kabupaten' => 'Sumba Barat','provinsi_id' => '53'],
  ['id' => '304','kabupaten_id' => '5312','nama_kabupaten' => 'Sumba Timur','provinsi_id' => '53'],
  ['id' => '305','kabupaten_id' => '5313','nama_kabupaten' => 'Lembata','provinsi_id' => '53'],
  ['id' => '306','kabupaten_id' => '5314','nama_kabupaten' => 'Rote Ndao','provinsi_id' => '53'],
  ['id' => '307','kabupaten_id' => '5315','nama_kabupaten' => 'Manggarai Barat','provinsi_id' => '53'],
  ['id' => '308','kabupaten_id' => '5321','nama_kabupaten' => 'Malaka','provinsi_id' => '53'],
  ['id' => '309','kabupaten_id' => '5316','nama_kabupaten' => 'Nagekeo','provinsi_id' => '53'],
  ['id' => '310','kabupaten_id' => '5317','nama_kabupaten' => 'Sumba Tengah','provinsi_id' => '53'],
  ['id' => '311','kabupaten_id' => '5318','nama_kabupaten' => 'Sumba Barat Daya','provinsi_id' => '53'],
  ['id' => '312','kabupaten_id' => '5319','nama_kabupaten' => 'Manggarai Timur','provinsi_id' => '53'],
  ['id' => '313','kabupaten_id' => '5320','nama_kabupaten' => 'Sabu Raijua','provinsi_id' => '53'],
  ['id' => '314','kabupaten_id' => '5371','nama_kabupaten' => 'Kota Kupang','provinsi_id' => '53'],
  ['id' => '315','kabupaten_id' => '6101','nama_kabupaten' => 'Sambas','provinsi_id' => '61'],
  ['id' => '316','kabupaten_id' => '6102','nama_kabupaten' => 'Mempawah','provinsi_id' => '61'],
  ['id' => '317','kabupaten_id' => '6103','nama_kabupaten' => 'Sanggau','provinsi_id' => '61'],
  ['id' => '318','kabupaten_id' => '6104','nama_kabupaten' => 'Ketapang','provinsi_id' => '61'],
  ['id' => '319','kabupaten_id' => '6105','nama_kabupaten' => 'Sintang','provinsi_id' => '61'],
  ['id' => '320','kabupaten_id' => '6106','nama_kabupaten' => 'Kapuas Hulu','provinsi_id' => '61'],
  ['id' => '321','kabupaten_id' => '6108','nama_kabupaten' => 'Landak','provinsi_id' => '61'],
  ['id' => '322','kabupaten_id' => '6107','nama_kabupaten' => 'Bengkayang','provinsi_id' => '61'],
  ['id' => '323','kabupaten_id' => '6109','nama_kabupaten' => 'Melawi','provinsi_id' => '61'],
  ['id' => '324','kabupaten_id' => '6110','nama_kabupaten' => 'Sekadau','provinsi_id' => '61'],
  ['id' => '325','kabupaten_id' => '6111','nama_kabupaten' => 'Kayong Utara','provinsi_id' => '61'],
  ['id' => '326','kabupaten_id' => '6112','nama_kabupaten' => 'Kubu Raya','provinsi_id' => '61'],
  ['id' => '327','kabupaten_id' => '6171','nama_kabupaten' => 'Kota Pontianak','provinsi_id' => '61'],
  ['id' => '328','kabupaten_id' => '6172','nama_kabupaten' => 'Kota Singkawang','provinsi_id' => '61'],
  ['id' => '329','kabupaten_id' => '6201','nama_kabupaten' => 'Kotawaringin Barat','provinsi_id' => '62'],
  ['id' => '330','kabupaten_id' => '6203','nama_kabupaten' => 'Kapuas','provinsi_id' => '62'],
  ['id' => '331','kabupaten_id' => '6202','nama_kabupaten' => 'Kotawaringin Timur','provinsi_id' => '62'],
  ['id' => '332','kabupaten_id' => '6303','nama_kabupaten' => 'Banjar','provinsi_id' => '63'],
  ['id' => '333','kabupaten_id' => '6204','nama_kabupaten' => 'Barito Selatan','provinsi_id' => '62'],
  ['id' => '334','kabupaten_id' => '6401','nama_kabupaten' => 'Paser','provinsi_id' => '64'],
  ['id' => '335','kabupaten_id' => '6205','nama_kabupaten' => 'Barito Utara','provinsi_id' => '62'],
  ['id' => '336','kabupaten_id' => '6403','nama_kabupaten' => 'Berau','provinsi_id' => '64'],
  ['id' => '337','kabupaten_id' => '6206','nama_kabupaten' => 'Katingan','provinsi_id' => '62'],
  ['id' => '338','kabupaten_id' => '6207','nama_kabupaten' => 'Seruyan','provinsi_id' => '62'],
  ['id' => '339','kabupaten_id' => '6208','nama_kabupaten' => 'Sukamara','provinsi_id' => '62'],
  ['id' => '340','kabupaten_id' => '6209','nama_kabupaten' => 'Lamandau','provinsi_id' => '62'],
  ['id' => '341','kabupaten_id' => '6210','nama_kabupaten' => 'Gunung Mas','provinsi_id' => '62'],
  ['id' => '342','kabupaten_id' => '6211','nama_kabupaten' => 'Pulang Pisau','provinsi_id' => '62'],
  ['id' => '343','kabupaten_id' => '7171','nama_kabupaten' => 'Kota Manado','provinsi_id' => '71'],
  ['id' => '344','kabupaten_id' => '6212','nama_kabupaten' => 'Murung Raya','provinsi_id' => '62'],
  ['id' => '345','kabupaten_id' => '6213','nama_kabupaten' => 'Barito Timur','provinsi_id' => '62'],
  ['id' => '346','kabupaten_id' => '6271','nama_kabupaten' => 'Kota Palangka Raya','provinsi_id' => '62'],
  ['id' => '347','kabupaten_id' => '6301','nama_kabupaten' => 'Tanah Laut','provinsi_id' => '63'],
  ['id' => '348','kabupaten_id' => '6302','nama_kabupaten' => 'Kota Baru','provinsi_id' => '63'],
  ['id' => '349','kabupaten_id' => '7201','nama_kabupaten' => 'Banggai','provinsi_id' => '72'],
  ['id' => '350','kabupaten_id' => '7202','nama_kabupaten' => 'Poso','provinsi_id' => '72'],
  ['id' => '351','kabupaten_id' => '6304','nama_kabupaten' => 'Barito Kuala','provinsi_id' => '63'],
  ['id' => '352','kabupaten_id' => '6305','nama_kabupaten' => 'Tapin','provinsi_id' => '63'],
  ['id' => '353','kabupaten_id' => '6306','nama_kabupaten' => 'Hulu Sungai Selatan','provinsi_id' => '63'],
  ['id' => '354','kabupaten_id' => '6307','nama_kabupaten' => 'Hulu Sungai Tengah','provinsi_id' => '63'],
  ['id' => '355','kabupaten_id' => '6308','nama_kabupaten' => 'Hulu Sungai Utara','provinsi_id' => '63'],
  ['id' => '356','kabupaten_id' => '6309','nama_kabupaten' => 'Tabalong','provinsi_id' => '63'],
  ['id' => '357','kabupaten_id' => '6310','nama_kabupaten' => 'Tanah Bumbu','provinsi_id' => '63'],
  ['id' => '358','kabupaten_id' => '6311','nama_kabupaten' => 'Balangan','provinsi_id' => '63'],
  ['id' => '359','kabupaten_id' => '6371','nama_kabupaten' => 'Kota Banjarmasin','provinsi_id' => '63'],
  ['id' => '360','kabupaten_id' => '6372','nama_kabupaten' => 'Kota Banjar Baru','provinsi_id' => '63'],
  ['id' => '361','kabupaten_id' => '6402','nama_kabupaten' => 'Kutai Kartanegara','provinsi_id' => '64'],
  ['id' => '362','kabupaten_id' => '6407','nama_kabupaten' => 'Kutai Barat','provinsi_id' => '64'],
  ['id' => '363','kabupaten_id' => '6408','nama_kabupaten' => 'Kutai Timur','provinsi_id' => '64'],
  ['id' => '364','kabupaten_id' => '6409','nama_kabupaten' => 'Penajam Paser Utara','provinsi_id' => '64'],
  ['id' => '365','kabupaten_id' => '6411','nama_kabupaten' => 'Mahakam Ulu','provinsi_id' => '64'],
  ['id' => '366','kabupaten_id' => '6471','nama_kabupaten' => 'Kota Balikpapan','provinsi_id' => '64'],
  ['id' => '367','kabupaten_id' => '6472','nama_kabupaten' => 'Kota Samarinda','provinsi_id' => '64'],
  ['id' => '368','kabupaten_id' => '6474','nama_kabupaten' => 'Kota Bontang','provinsi_id' => '64'],
  ['id' => '369','kabupaten_id' => '6501','nama_kabupaten' => 'Bulungan','provinsi_id' => '65'],
  ['id' => '370','kabupaten_id' => '6502','nama_kabupaten' => 'Malinau','provinsi_id' => '65'],
  ['id' => '371','kabupaten_id' => '6503','nama_kabupaten' => 'Nunukan','provinsi_id' => '65'],
  ['id' => '372','kabupaten_id' => '6504','nama_kabupaten' => 'Tana Tidung','provinsi_id' => '65'],
  ['id' => '373','kabupaten_id' => '6571','nama_kabupaten' => 'Kota Tarakan','provinsi_id' => '65'],
  ['id' => '374','kabupaten_id' => '7101','nama_kabupaten' => 'Bolaang Mongondow','provinsi_id' => '71'],
  ['id' => '375','kabupaten_id' => '7102','nama_kabupaten' => 'Minahasa','provinsi_id' => '71'],
  ['id' => '376','kabupaten_id' => '7103','nama_kabupaten' => 'Kepulauan Sangihe','provinsi_id' => '71'],
  ['id' => '377','kabupaten_id' => '7203','nama_kabupaten' => 'Donggala','provinsi_id' => '72'],
  ['id' => '378','kabupaten_id' => '7104','nama_kabupaten' => 'Kepulauan Talaud','provinsi_id' => '71'],
  ['id' => '379','kabupaten_id' => '7105','nama_kabupaten' => 'Minahasa Selatan','provinsi_id' => '71'],
  ['id' => '380','kabupaten_id' => '7106','nama_kabupaten' => 'Minahasa Utara','provinsi_id' => '71'],
  ['id' => '381','kabupaten_id' => '7107','nama_kabupaten' => 'Bolaang Mongondow Utara','provinsi_id' => '71'],
  ['id' => '382','kabupaten_id' => '7108','nama_kabupaten' => 'Minahasa Tenggara','provinsi_id' => '71'],
  ['id' => '383','kabupaten_id' => '7109','nama_kabupaten' => 'Kepulauan Siau Tagulandang Biaro [Sitaro]','provinsi_id' => '71'],
  ['id' => '384','kabupaten_id' => '7110','nama_kabupaten' => 'Bolaang Mongondow Timur','provinsi_id' => '71'],
  ['id' => '385','kabupaten_id' => '7111','nama_kabupaten' => 'Bolaang Mongondow Selatan','provinsi_id' => '71'],
  ['id' => '386','kabupaten_id' => '7172','nama_kabupaten' => 'Kota Bitung','provinsi_id' => '71'],
  ['id' => '387','kabupaten_id' => '7173','nama_kabupaten' => 'Kota Tomohon','provinsi_id' => '71'],
  ['id' => '388','kabupaten_id' => '7174','nama_kabupaten' => 'Kota Kotamobagu','provinsi_id' => '71'],
  ['id' => '389','kabupaten_id' => '7204','nama_kabupaten' => 'Toli-Toli','provinsi_id' => '72'],
  ['id' => '390','kabupaten_id' => '7205','nama_kabupaten' => 'Buol','provinsi_id' => '72'],
  ['id' => '391','kabupaten_id' => '7206','nama_kabupaten' => 'Morowali','provinsi_id' => '72'],
  ['id' => '392','kabupaten_id' => '7207','nama_kabupaten' => 'Banggai Kepulauan','provinsi_id' => '72'],
  ['id' => '393','kabupaten_id' => '7208','nama_kabupaten' => 'Parigi Moutong','provinsi_id' => '72'],
  ['id' => '394','kabupaten_id' => '7210','nama_kabupaten' => 'Sigi','provinsi_id' => '72'],
  ['id' => '395','kabupaten_id' => '7209','nama_kabupaten' => 'Tojo Una-Una','provinsi_id' => '72'],
  ['id' => '396','kabupaten_id' => '7211','nama_kabupaten' => 'Banggai Laut','provinsi_id' => '72'],
  ['id' => '397','kabupaten_id' => '7212','nama_kabupaten' => 'Morowali Utara','provinsi_id' => '72'],
  ['id' => '398','kabupaten_id' => '7271','nama_kabupaten' => 'Kota Palu','provinsi_id' => '72'],
  ['id' => '399','kabupaten_id' => '7301','nama_kabupaten' => 'Kepulauan Selayar','provinsi_id' => '73'],
  ['id' => '400','kabupaten_id' => '7302','nama_kabupaten' => 'Bulukumba','provinsi_id' => '73'],
  ['id' => '401','kabupaten_id' => '7308','nama_kabupaten' => 'Bone','provinsi_id' => '73'],
  ['id' => '402','kabupaten_id' => '7303','nama_kabupaten' => 'Bantaeng','provinsi_id' => '73'],
  ['id' => '403','kabupaten_id' => '7304','nama_kabupaten' => 'Jeneponto','provinsi_id' => '73'],
  ['id' => '404','kabupaten_id' => '7305','nama_kabupaten' => 'Takalar','provinsi_id' => '73'],
  ['id' => '405','kabupaten_id' => '7306','nama_kabupaten' => 'Gowa','provinsi_id' => '73'],
  ['id' => '406','kabupaten_id' => '7307','nama_kabupaten' => 'Sinjai','provinsi_id' => '73'],
  ['id' => '407','kabupaten_id' => '7309','nama_kabupaten' => 'Maros','provinsi_id' => '73'],
  ['id' => '408','kabupaten_id' => '7310','nama_kabupaten' => 'Pangkajene Kepulauan','provinsi_id' => '73'],
  ['id' => '409','kabupaten_id' => '7311','nama_kabupaten' => 'Barru','provinsi_id' => '73'],
  ['id' => '410','kabupaten_id' => '7312','nama_kabupaten' => 'Soppeng','provinsi_id' => '73'],
  ['id' => '411','kabupaten_id' => '7313','nama_kabupaten' => 'Wajo','provinsi_id' => '73'],
  ['id' => '412','kabupaten_id' => '7314','nama_kabupaten' => 'Sidenreng Rappang','provinsi_id' => '73'],
  ['id' => '413','kabupaten_id' => '7315','nama_kabupaten' => 'Pinrang','provinsi_id' => '73'],
  ['id' => '414','kabupaten_id' => '7316','nama_kabupaten' => 'Enrekang','provinsi_id' => '73'],
  ['id' => '415','kabupaten_id' => '7317','nama_kabupaten' => 'Luwu','provinsi_id' => '73'],
  ['id' => '416','kabupaten_id' => '7318','nama_kabupaten' => 'Tana Toraja','provinsi_id' => '73'],
  ['id' => '417','kabupaten_id' => '7324','nama_kabupaten' => 'Luwu Timur','provinsi_id' => '73'],
  ['id' => '418','kabupaten_id' => '7319','nama_kabupaten' => 'Toraja Utara','provinsi_id' => '73'],
  ['id' => '419','kabupaten_id' => '7401','nama_kabupaten' => 'Kolaka','provinsi_id' => '74'],
  ['id' => '420','kabupaten_id' => '7322','nama_kabupaten' => 'Luwu Utara','provinsi_id' => '73'],
  ['id' => '421','kabupaten_id' => '7371','nama_kabupaten' => 'Kota Makassar','provinsi_id' => '73'],
  ['id' => '422','kabupaten_id' => '7372','nama_kabupaten' => 'Kota Parepare','provinsi_id' => '73'],
  ['id' => '423','kabupaten_id' => '7373','nama_kabupaten' => 'Kota Palopo','provinsi_id' => '73'],
  ['id' => '424','kabupaten_id' => '7402','nama_kabupaten' => 'Konawe','provinsi_id' => '74'],
  ['id' => '425','kabupaten_id' => '7403','nama_kabupaten' => 'Muna','provinsi_id' => '74'],
  ['id' => '426','kabupaten_id' => '7404','nama_kabupaten' => 'Buton','provinsi_id' => '74'],
  ['id' => '427','kabupaten_id' => '7405','nama_kabupaten' => 'Konawe Selatan','provinsi_id' => '74'],
  ['id' => '428','kabupaten_id' => '7414','nama_kabupaten' => 'Buton Tengah','provinsi_id' => '74'],
  ['id' => '429','kabupaten_id' => '7501','nama_kabupaten' => 'Gorontalo','provinsi_id' => '75'],
  ['id' => '430','kabupaten_id' => '7406','nama_kabupaten' => 'Bombana','provinsi_id' => '74'],
  ['id' => '431','kabupaten_id' => '7407','nama_kabupaten' => 'Wakatobi','provinsi_id' => '74'],
  ['id' => '432','kabupaten_id' => '7408','nama_kabupaten' => 'Kolaka Utara','provinsi_id' => '74'],
  ['id' => '433','kabupaten_id' => '7409','nama_kabupaten' => 'Buton Utara','provinsi_id' => '74'],
  ['id' => '434','kabupaten_id' => '7410','nama_kabupaten' => 'Konawe Utara','provinsi_id' => '74'],
  ['id' => '435','kabupaten_id' => '7411','nama_kabupaten' => 'Kolaka Timur','provinsi_id' => '74'],
  ['id' => '436','kabupaten_id' => '7412','nama_kabupaten' => 'Konawe Kepulauan','provinsi_id' => '74'],
  ['id' => '437','kabupaten_id' => '7413','nama_kabupaten' => 'Buton Selatan','provinsi_id' => '74'],
  ['id' => '438','kabupaten_id' => '7415','nama_kabupaten' => 'Muna Barat','provinsi_id' => '74'],
  ['id' => '439','kabupaten_id' => '7471','nama_kabupaten' => 'Kota Kendari','provinsi_id' => '74'],
  ['id' => '440','kabupaten_id' => '7472','nama_kabupaten' => 'Kota Bau-Bau','provinsi_id' => '74'],
  ['id' => '441','kabupaten_id' => '7502','nama_kabupaten' => 'Boalemo','provinsi_id' => '75'],
  ['id' => '442','kabupaten_id' => '7503','nama_kabupaten' => 'Bone Bolango','provinsi_id' => '75'],
  ['id' => '443','kabupaten_id' => '7504','nama_kabupaten' => 'Pohuwato','provinsi_id' => '75'],
  ['id' => '444','kabupaten_id' => '7505','nama_kabupaten' => 'Gorontalo Utara','provinsi_id' => '75'],
  ['id' => '445','kabupaten_id' => '7571','nama_kabupaten' => 'Kota Gorontalo','provinsi_id' => '75'],
  ['id' => '446','kabupaten_id' => '7601','nama_kabupaten' => 'Mamuju Utara','provinsi_id' => '76'],
  ['id' => '447','kabupaten_id' => '7602','nama_kabupaten' => 'Mamuju','provinsi_id' => '76'],
  ['id' => '448','kabupaten_id' => '7603','nama_kabupaten' => 'Mamasa','provinsi_id' => '76'],
  ['id' => '449','kabupaten_id' => '7604','nama_kabupaten' => 'Polewali Mandar','provinsi_id' => '76'],
  ['id' => '450','kabupaten_id' => '7605','nama_kabupaten' => 'Majene','provinsi_id' => '76'],
  ['id' => '451','kabupaten_id' => '7606','nama_kabupaten' => 'Mamuju Tengah','provinsi_id' => '76'],
  ['id' => '452','kabupaten_id' => '8101','nama_kabupaten' => 'Maluku Tengah','provinsi_id' => '81'],
  ['id' => '453','kabupaten_id' => '8102','nama_kabupaten' => 'Maluku Tenggara','provinsi_id' => '81'],
  ['id' => '454','kabupaten_id' => '8103','nama_kabupaten' => 'Maluku Tenggara Barat','provinsi_id' => '81'],
  ['id' => '455','kabupaten_id' => '8104','nama_kabupaten' => 'Buru','provinsi_id' => '81'],
  ['id' => '456','kabupaten_id' => '8105','nama_kabupaten' => 'Seram Bagian Timur','provinsi_id' => '81'],
  ['id' => '457','kabupaten_id' => '8106','nama_kabupaten' => 'Seram Bagian Barat','provinsi_id' => '81'],
  ['id' => '458','kabupaten_id' => '8107','nama_kabupaten' => 'Kepulauan Aru','provinsi_id' => '81'],
  ['id' => '459','kabupaten_id' => '8108','nama_kabupaten' => 'Maluku Barat Daya','provinsi_id' => '81'],
  ['id' => '460','kabupaten_id' => '8109','nama_kabupaten' => 'Buru Selatan','provinsi_id' => '81'],
  ['id' => '461','kabupaten_id' => '8171','nama_kabupaten' => 'Kota Ambon','provinsi_id' => '81'],
  ['id' => '462','kabupaten_id' => '8172','nama_kabupaten' => 'Kota Tual','provinsi_id' => '81'],
  ['id' => '463','kabupaten_id' => '8201','nama_kabupaten' => 'Halmahera Barat','provinsi_id' => '82'],
  ['id' => '464','kabupaten_id' => '8202','nama_kabupaten' => 'Halmahera Tengah','provinsi_id' => '82'],
  ['id' => '465','kabupaten_id' => '8203','nama_kabupaten' => 'Halmahera Utara','provinsi_id' => '82'],
  ['id' => '466','kabupaten_id' => '8204','nama_kabupaten' => 'Halmahera Selatan','provinsi_id' => '82'],
  ['id' => '467','kabupaten_id' => '8205','nama_kabupaten' => 'Kepulauan Sula','provinsi_id' => '82'],
  ['id' => '468','kabupaten_id' => '9101','nama_kabupaten' => 'Merauke','provinsi_id' => '91'],
  ['id' => '469','kabupaten_id' => '8206','nama_kabupaten' => 'Halmahera Timur','provinsi_id' => '82'],
  ['id' => '470','kabupaten_id' => '8207','nama_kabupaten' => 'Pulau Morotai','provinsi_id' => '82'],
  ['id' => '471','kabupaten_id' => '8208','nama_kabupaten' => 'Pulau Taliabu','provinsi_id' => '82'],
  ['id' => '472','kabupaten_id' => '8271','nama_kabupaten' => 'Kota Ternate','provinsi_id' => '82'],
  ['id' => '473','kabupaten_id' => '8272','nama_kabupaten' => 'Kota Tidore Kepulauan','provinsi_id' => '82'],
  ['id' => '474','kabupaten_id' => '9102','nama_kabupaten' => 'Jayawijaya','provinsi_id' => '91'],
  ['id' => '475','kabupaten_id' => '9103','nama_kabupaten' => 'Jayapura','provinsi_id' => '91'],
  ['id' => '476','kabupaten_id' => '9104','nama_kabupaten' => 'Nabire','provinsi_id' => '91'],
  ['id' => '477','kabupaten_id' => '9105','nama_kabupaten' => 'Kepulauan Yapen','provinsi_id' => '91'],
  ['id' => '478','kabupaten_id' => '9106','nama_kabupaten' => 'Biak Numfor','provinsi_id' => '91'],
  ['id' => '479','kabupaten_id' => '9107','nama_kabupaten' => 'Puncak Jaya','provinsi_id' => '91'],
  ['id' => '480','kabupaten_id' => '9108','nama_kabupaten' => 'Paniai','provinsi_id' => '91'],
  ['id' => '481','kabupaten_id' => '9109','nama_kabupaten' => 'Mimika','provinsi_id' => '91'],
  ['id' => '482','kabupaten_id' => '9110','nama_kabupaten' => 'Sarmi','provinsi_id' => '91'],
  ['id' => '483','kabupaten_id' => '9111','nama_kabupaten' => 'Keerom','provinsi_id' => '91'],
  ['id' => '484','kabupaten_id' => '9112','nama_kabupaten' => 'Pegunungan Bintang','provinsi_id' => '91'],
  ['id' => '485','kabupaten_id' => '9113','nama_kabupaten' => 'Yahukimo','provinsi_id' => '91'],
  ['id' => '486','kabupaten_id' => '9114','nama_kabupaten' => 'Tolikara','provinsi_id' => '91'],
  ['id' => '487','kabupaten_id' => '9115','nama_kabupaten' => 'Waropen','provinsi_id' => '91'],
  ['id' => '488','kabupaten_id' => '9116','nama_kabupaten' => 'Boven Digoel','provinsi_id' => '91'],
  ['id' => '489','kabupaten_id' => '9117','nama_kabupaten' => 'Mappi','provinsi_id' => '91'],
  ['id' => '490','kabupaten_id' => '9118','nama_kabupaten' => 'Asmat','provinsi_id' => '91'],
  ['id' => '491','kabupaten_id' => '9119','nama_kabupaten' => 'Lanny Jaya','provinsi_id' => '91'],
  ['id' => '492','kabupaten_id' => '9120','nama_kabupaten' => 'Nduga','provinsi_id' => '91'],
  ['id' => '493','kabupaten_id' => '9121','nama_kabupaten' => 'Supiori','provinsi_id' => '91'],
  ['id' => '494','kabupaten_id' => '9122','nama_kabupaten' => 'Intan Jaya','provinsi_id' => '91'],
  ['id' => '495','kabupaten_id' => '9123','nama_kabupaten' => 'Puncak','provinsi_id' => '91'],
  ['id' => '496','kabupaten_id' => '9124','nama_kabupaten' => 'Deiyai','provinsi_id' => '91'],
  ['id' => '497','kabupaten_id' => '9125','nama_kabupaten' => 'Dogiyai','provinsi_id' => '91'],
  ['id' => '498','kabupaten_id' => '9126','nama_kabupaten' => 'Yalimo','provinsi_id' => '91'],
  ['id' => '499','kabupaten_id' => '9127','nama_kabupaten' => 'Mamberamo Tengah','provinsi_id' => '91'],
  ['id' => '500','kabupaten_id' => '9128','nama_kabupaten' => 'Mamberamo Raya','provinsi_id' => '91'],
  ['id' => '501','kabupaten_id' => '9171','nama_kabupaten' => 'Kota Jayapura','provinsi_id' => '91'],
  ['id' => '502','kabupaten_id' => '9201','nama_kabupaten' => 'Sorong','provinsi_id' => '92'],
  ['id' => '503','kabupaten_id' => '9202','nama_kabupaten' => 'Manokwari','provinsi_id' => '92'],
  ['id' => '504','kabupaten_id' => '9203','nama_kabupaten' => 'Fakfak','provinsi_id' => '92'],
  ['id' => '505','kabupaten_id' => '9204','nama_kabupaten' => 'Sorong Selatan','provinsi_id' => '92'],
  ['id' => '506','kabupaten_id' => '9205','nama_kabupaten' => 'Raja Ampat','provinsi_id' => '92'],
  ['id' => '507','kabupaten_id' => '9206','nama_kabupaten' => 'Teluk Bintuni','provinsi_id' => '92'],
  ['id' => '508','kabupaten_id' => '9207','nama_kabupaten' => 'Teluk Wondama','provinsi_id' => '92'],
  ['id' => '509','kabupaten_id' => '9208','nama_kabupaten' => 'Kaimana','provinsi_id' => '92'],
  ['id' => '510','kabupaten_id' => '9209','nama_kabupaten' => 'Maybrat','provinsi_id' => '92'],
  ['id' => '511','kabupaten_id' => '9210','nama_kabupaten' => 'Tambrauw','provinsi_id' => '92'],
  ['id' => '512','kabupaten_id' => '9211','nama_kabupaten' => 'Pegunungan Arfak','provinsi_id' => '92'],
  ['id' => '513','kabupaten_id' => '9212','nama_kabupaten' => 'Manokwari Selatan','provinsi_id' => '92'],
  ['id' => '514','kabupaten_id' => '9271','nama_kabupaten' => 'Kota Sorong','provinsi_id' => '92'],

        ]);
    }
}
